all:
  children:
    DC1:
      children:
        spines_DC1:
          hosts:
            spine[1:3]-DC1:
        leafs_DC1:
          hosts:
            leaf[1:4]-DC1:
            borderleaf[1:2]-DC1:
    DC2:
      children:
        spines_DC2:
          hosts:
            spine[1:3]-DC2:
        leafs_DC2:
          hosts:
            leaf[1:4]-DC2:
            borderleaf[1:2]-DC2:
    DCIs:
      hosts:
        DCI:
  vars:
    ansible_connection: network_cli
    ansible_network_os: eos
    ansible_become: yes
    ansible_become_method: enable
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: arista