---
- hosts: leafs_DC1, leafs_DC2
  gather_facts: no
  tasks:
  - name: Create MLAG template
    template:
      src: "{{lookup('env','PWD')}}/templates/mlag.j2"
      dest: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_mlag.cfg"
  - name: Upload config
    eos_config:
      src: "{{lookup('env','PWD')}}/configs/{{inventory_hostname}}_mlag.cfg"